name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Setup Dotnet 2.2.300
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.6.1'

    - name: 'Run dotnet'
      shell: pwsh
      run: |
        # If your function app project is not located in your repository's root
        # Please change your directory for dotnet build in pushd
        pushd ./PartsUnlimited-aspnet45/
        dotnet build --configuration Release --output ./output
        popd

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o myapp 
        
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: mydotnetcoreapp # Replace with your app name
        publish-profile: ${{ secrets.azureWebAppPublishProfile }} # Define secret variable in repository settings as per action documentation
        package: './myapp' 
    
